spring.application.name=product_service

server.port=5003


# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/product-db

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:5001/eureka/
